### ISSUE TITLE
Unnecessary files committed

### ISSUE THREAD

**Issue by Nemesis-AS** [ExtraLongBaguette/Flappy-Game#9]
Currently the repo has `.import` files and exported files present as well. Consider adding a `.gitignore` to the project so `.import` and exported files don't get committed as those can be generated by Godot.

**Comment by lauri-lyytikainen** [comment]
Good idea
This is my first time using GitHub or Git in general so still have a lot to learn

**Comment by Nemesis-AS** [comment]
Don't worry, things would be good once you get used to them ^^
Nice work on the game btw

**Comment by lauri-lyytikainen** [comment]
Taken care in #11

**Comment by Nemesis-AS** [comment]
The files that have already been committed still need to be removed
